# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-14 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('status', models.CharField(default='absent', max_length=30)),
            ],
        ),
    ]
