# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-16 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pupil'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='arrive_time',
            field=models.DateTimeField(blank=True, default="some string", verbose_name='date arrive'),
            preserve_default=False,
        ),
    ]
