# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-23 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pupil_arrive_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='non_attendance',
            field=models.IntegerField(default=0),
        ),
    ]
