# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-23 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pupil_non_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='grade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='qrcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='status',
            field=models.CharField(default='absent', max_length=50),
        ),
    ]
