# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-23 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181223_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='photo',
            field=models.ImageField(default='media/images/default.jpg', upload_to='/media/images'),
        ),
    ]
