# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-04 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181223_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=70)),
                ('school_name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=300)),
                ('date', models.DateTimeField(verbose_name='order date')),
            ],
        ),
        migrations.AlterField(
            model_name='pupil',
            name='arrive_time',
            field=models.DateTimeField(verbose_name='date arrive'),
        ),
    ]
