# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-30 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190105_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='arrive_time',
            field=models.TimeField(verbose_name='time arrive'),
        ),
    ]
