# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-30 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190130_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='location',
            field=models.CharField(choices=[('urban', 'Городской'), ('boarding', 'Интернат'), ('relativity', 'У родственников')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='status',
            field=models.CharField(choices=[('absent', 'Отсутствует'), ('present', 'Присутствует'), ('ill', 'Болен'), ('reason', 'Уважительная причина')], default='absent', max_length=50),
        ),
    ]
