# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190130_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='arrive_time',
            field=models.TimeField(default=datetime.datetime(2019, 1, 31, 12, 51, 31, 665339, tzinfo=utc), verbose_name='time arrive'),
        ),
    ]
