# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-02 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190130_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='grade',
            field=models.CharField(choices=[('11ФМ', '11 физико-математический')], max_length=50),
        ),
    ]
