# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 12:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190131_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='arrive_time',
            field=models.TimeField(default=datetime.time(12, 52, 4, 214319), verbose_name='time arrive'),
        ),
    ]
