# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-31 13:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190131_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='arrive_time',
            field=models.TimeField(default=datetime.time(22, 2, 35, 645512), verbose_name='time arrive'),
        ),
    ]
