# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-02 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190202_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='arrive_time',
            field=models.TimeField(blank=True, null=True, verbose_name='time arrive'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='grade',
            field=models.CharField(choices=[('11FM', '11 физико-математический класс'), ('11ENG', '11 инженерный класс'), ('11TECH', '11 технический класс'), ('11PTH', '11 политехнический класс'), ('11BCH', '11 биолого-химический класс'), ('11HUM', '11 гуманитарный класс'), ('10FM', '10 физико-математический'), ('10ENG', '10 инженерный класс'), ('10TECH', '10 технический класс'), ('10PTH', '10 политехнический класс'), ('10BCH', '10 биолого-химический класс'), ('10HUM', '10 гуманитарный класс'), ('9 класс', '9'), ('8 класс', '8'), ('7 класс', '7'), ('6 класс', '6'), ('5 класс', '5')], max_length=50),
        ),
    ]
