# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-02 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190131_2203'),
        ('main', '0020_auto_20190202_1511'),
    ]

    operations = [
    ]
