# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-06 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190202_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='eating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pupil',
            name='inboard',
            field=models.BooleanField(default=True),
        ),
    ]
