# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-15 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20190212_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='event time')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pupil',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Event'),
        ),
    ]
