# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-15 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20190215_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Event'),
        ),
    ]
