# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-12 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20190215_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='index',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
