# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-24 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_pupil_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupil', models.ManyToManyField(to='main.Pupil')),
            ],
        ),
    ]
