# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-24 10:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 3, 24, 10, 29, 21, 778151, tzinfo=utc), verbose_name='date'),
            preserve_default=False,
        ),
    ]
