# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-24 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_day_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='order date'),
        ),
    ]
