# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-24 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20190324_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='pupil',
            field=models.ManyToManyField(blank=True, null=True, to='main.Pupil'),
        ),
    ]
